name: GSL
version: '${project.version}'
main: me.zombie_striker.gsl.GSLCore
api-version: 1.19
authors: [ Zombie_Striker ]
softdepend:
  - 'Terra'
commands:
  r:
    aliases: ['reinforce']
  g:
    aliases: ['group']
  nlcg:
    description: "create new namelayer"
  nl:
    description: "Namelayer commands"
  nations:
    description: "Namelayer commands"
  nlad:
    description: "Namelayer commands"
  nlmerge:
    description: "Namelayer commands"
  nldisband:
    description: "Namelayer commands"
  nlinvite:
    description: "Namelayer commands"
  nlremove:
    description: "Namelayer commands"
  nlaccept:
    description: "Namelayer commands"
  tb:
    aliases: ['tradingbooth']
